### ISSUE TITLE
Third party compatibility: Tainacan

### ISSUE THREAD

**Issue by mateuswetah** [wikimedia/wikipediapreview-wordpress#96]
Hi there, thank you for the amazing plugin!

I'm one of the authors of [Tainacan](tainacan.org/), a digital repository plugin for WordPress that is used mostly by Museums and Libraries. One of our users recently asked us about integration with Wikipedia Preview:
https://tainacan.discourse.group/t/usando-plugin-wikipedia-preview-com-tainacan/1646/2

I would like to work on that. I'm aware that the [original JS library ](https://github.com/wikimedia/wikipedia-preview) could be used for this, but it would be even better if the feature and its dependencies are tied to the usage of the plugin in the WordPress site. 

Our situation is the following:

- Our Collections and Items are all Custom Post Types, with Custom Meta Fields ( which we call metadata);
- Users can create metadata for them of different types, including `textarea`, where adding basic format and links is available;
- Due to this "structured data" logic, our post content is not meant to be edited neither in the classic nor inside Gutenberg, we have our own UI for that, all with custom forms, but the inner structure remains the same, posts and meta fields edited via the rest api.
- My goal is that if a user inserts a link to Wikipedia inside one of this `textarea` metadata, the HTML processed version of the content displays the tooltip, just like what happens in the classic editor (no autocomplete search by now, we can think on this later). I can think of a few hooks where we could add some information to the final displayed version of the data;

Do you think it could be possible? Could you provide some insight so I can implement this feature somehow?

BTW, we have some plans for integrating our metadata mappers with Wikidata, maybe we can talk about there in the future :)

**Comment by mateuswetah** [comment]
Uhmm actually, a bit of searching in the code maybe me see how simple it can be :)

Could you provide a hook where developers could insert extra post types to this array?
https://github.com/wikimedia/wikipediapreview-wordpress/blob/2c087d8209d102596bdaf016dd8b4bb03192e071/wikipediapreview.php#L19
https://github.com/wikimedia/wikipediapreview-wordpress/blob/2c087d8209d102596bdaf016dd8b4bb03192e071/wikipediapreview.php#L66

This should be enough to attend me and other extenders (say someone wants a WikiPedia preview in their WooCommerce Product description...)

**Comment by mateuswetah** [comment]
Added a pull request here in case you are interested:
https://github.com/wikimedia/wikipediapreview-wordpress/pull/97

**Comment by hueitan** [comment]
Thanks @mateuswetah, we actually have one ticket on this topic https://phabricator.wikimedia.org/T340566, we are looking for the generic solution without user input if that is possible. 

From your experience do you think this is doable?

**Comment by mateuswetah** [comment]
@hueitan Uhm...

Well, we could proactively avoid post types that are internally used by WordPress stuff, such as the `customize_widget`, `revision`, `block`, `customize_changeset`... maybe one of them was the cause for the error.

Looking at the object received by the [register_custom_post_type()](https://developer.wordpress.org/reference/functions/register_post_type/) function, the `public`attribute may be one criteria for deciding that. Or maybe the `_builtin`, but I'm not sure if there is a function for retrieving that.

**Comment by hueitan** [comment]
Thanks again for the idea @mateuswetah we will try to fix this the earliest next week, I will update you here. This is our next priority now as many are requested this.

**Comment by stephanebisson** [comment]
Thanks @mateuswetah for working on this. We'll do some research to make it as automatic as possible but we will probably merge your hook solution as well as an escape hatch.

**Comment by stephanebisson** [comment]
On a very simple local install, running this code:
```
$postTypes = get_post_types( array(), 'objects' );
$publicPostTypes = [];
foreach( $postTypes as $postType ) {
	if ( $postType->public ) {
		$publicPostTypes[] = $postType->name;
	}
}
print_r( $publicPostTypes );
```
returns
```
Array ( [0] => post [1] => page [2] => attachment )
```

So, of the 12 or so post types only 3 are public. @mateuswetah do you know if your custom post types are declared "public"?

**Comment by stephanebisson** [comment]
@mateuswetah I tried implementing your idea about public post types here #98 

I think ideally I will want to combine our 2 PRs to get the public post types, then run the hook for the final decision. 

Do you think it would be useful to have a form to configure the post types for those site admins who would be uncomfortable with writing a hook handler?

**Comment by mateuswetah** [comment]
> So, of the 12 or so post types only 3 are public. @mateuswetah do you know if your custom post types are declared "public"?

Yes :). They are all public.

> Do you think it would be useful to have a form to configure the post types for those site admins who would be uncomfortable with writing a hook handler?

Well yeesss but I think it is a really rare use case. I would leave this as a future improvement. If a developer can disable it via the hook it should be enough.

**Comment by stephanebisson** [comment]
@mateuswetah I updated my PR so it's easier to integrate with yours after it's merged.

**Comment by stephanebisson** [comment]
I merged both our PRs into a nice solution. Will be released in a few weeks.

**Comment by mateuswetah** [comment]
Thanks guys! Happy to collaborate somehow 🥂
